# Site settings
title: Sefa Öztürk
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ozturksefa.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sefa Öztürk
user_description: I'm a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. My blog page is coming soon...
user_title: Software Engineer
email: mailto:ozturkksefa@gmail.com
twitter_username: ozturkkksefa
gplus_username:  ozturkksefa
github_username:  ozturksefa


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
